---
# tasks file for ansible-role-vmware-dagger

- name: Create an empty vCenter IP:tag dictionary
  set_fact:
    vm_tag_pairs: {}
    
- name: Process vCenter tag list
  include_tasks: process_vm_tag.yml
  loop: '{{ vmware_tags }}'
  loop_control:
    loop_var: vm_tag_item

- name: Display the vCenter IP:tag dictionary
  debug:
    var: vm_tag_pairs

- name: Register the vCenter IP:tag dictionary
  panos_registered_ip:
    ip_address: '{{ panos_address }}'
    username: '{{ panos_username }}'
    password: '{{ panos_password }}'
    api_key: '{{ panos_api_key }}'
    ips: ['{{ vm_ip_item.key }}']
    tags: '{{ vm_ip_item.value }}'
    state: 'present'
  loop: '{{ vm_tag_pairs|dict2items }}'
  loop_control:
    loop_var: vm_ip_item

- name: Grab the firewall registered IP addresses
  panos_registered_ip_facts:
    ip_address: '{{ panos_address }}'
    username: '{{ panos_username }}'
    password: '{{ panos_password }}'
  register: fw_reg_ips_results

- name: Create the firewall IP:tag dictionary
  set_fact:
    fw_reg_ips: '{{ fw_reg_ips_results.results }}'

- name: Display the firewall IP:tag dictionary
  debug:
    var: fw_reg_ips

- name: Process each firewall IP:tag pair
  include_tasks: process_fw_ip.yml
  loop: "{{ fw_reg_ips | dict2items | subelements('value') }}"