---
# tasks file for ansible-role-vmware-dagger

- name: Register tagged vCenter virtual machines in PAN-OS DAGs
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_tag_pairs: []

  tasks:
  - name: Iterate over VM tags
    include: process_vm_tag.yml
    with_items: '{{ vmware_tags }}'
    loop_control:
      loop_var: vm_tag_item

#  - name: Display the vCenter tags
#    debug:
#      var: vm_tag_pairs

  - name: Grab the firewall registerd IP addresses
    panos_registered_ip_facts:
      ip_address: '{{ panos_address }}'
      username: '{{ panos_username }}'
      password: '{{ panos_password }}'
    register: fw_tag_pairs

  - name: Process each firewall tag pair
    include: process_fw_ip.yml
    with_items: '{{ fw_tag_pairs.key }}'
    loop_control:
      loop_var: fw_tag_item