- name: Unregister extraneous firewall IP:tag pairs
  panos_registered_ip:
    ip_address: '{{ panos_address }}'
    username: '{{ panos_username }}'
    password: '{{ panos_password }}'
    api_key: '{{ panos_api_key }}'
    ips: ['{{ item.0.key }}']
    tags: '{{ item.1 }}'
    state: 'absent'
  when: "( (vm_tag_pairs[item.0.key] is defined) and (item.1 not in vm_tag_pairs[item.0.key]) and (item.1 in vmware_tags) ) or ( (vm_tag_pairs[item.0.key] is not defined) and (item.1 in vmware_tags) )"