- name: Process the VM IP address
  set_fact:
    ipv6: '{{ ip_item.instance.ipv6 }}'

- set_fact:
    _tmplist: []

- set_fact:
    _tmplist: "{{ _tmplist + [vm_tag_item] }}"
  when: ipv6 | length > 0

- set_fact:
    _tmplist: "{{ _tmplist + vm_tag_pairs[ipv6] }}"
  when: ipv6 | length > 0 and vm_tag_pairs[ipv6] is defined

- name: Update the vCenter IP:tag dictionary
  set_fact:
    vm_tag_pairs: "{{ vm_tag_pairs | combine( {ipv6: _tmplist|unique} ) }}"
  when: ipv6 | length > 0